RISC-V: Fix compilation failed for frflags builtin in C++ mode.
- g++ will complain too few arguments for frflags builtin like bellow
message:

error: too few arguments to function 'unsigned int __builtin_riscv_frflags(void)'

The error is caused by frflagssi which is the overload function.